add postgres storage
adwski/shorty pull request #10
Opened 2023-12-12 22:41 UTC by adwski

2023-12-13 19:33 UTC, s-shpak requested changes

2023-12-13 19:33 UTC, s-shpak commented on cmd/shortener/main.go
> +		zap.NewExample().Fatal("cannot configure app", zap.Error(err))
Почему ты решил использовать `NewExample` ?

2023-12-13 19:33 UTC, s-shpak commented on docker/docker-compose.dev.yml
> +    #  - ./db/init/:/docker-entrypoint-initdb.d/
deadcode ? `db/init` может быть в репозитории

2023-12-13 19:33 UTC, s-shpak commented on docker/docker-compose.dev.yml
> +      - shorty-db:/var/lib/postgresql/data
Я бы складывал это в `tmp` лучше (в рабочем проекте это можно сделать параметризуемым)

2023-12-13 19:33 UTC, s-shpak commented on internal/middleware/recovering/recovering.go
> +		// Doesn't work here for some reason
А в чем это выражается?

2023-12-13 19:33 UTC, s-shpak commented on internal/app/app.go
> +	if statusSvc, err := status.New(&status.Config{Storage: cfg.Storage}); err == nil {
Я бы не стал ради этого добавлять логику: `Ping` для `MemoryStore` и `FileStore` может быть просто `nop`

2023-12-13 19:33 UTC, s-shpak commented on internal/app/config/config.go
> +	disableSSLOnMigration *bool) (storage Storage, err error) {
```suggestion
	disableSSLOnMigration *bool,
) (storage Storage, err error) {
```

2023-12-13 19:33 UTC, s-shpak commented on internal/services/shortener/batch.go
> +func (svc *Service) shortenBatch(ctx context.Context, batch []BatchURL) ([]BatchShortened, error) {
Эта функция делает несколько запросов к БД: в `genUniqueHash` и в `StoreBatch`, например, - значит все запросы должны быть обернуты в транзакцию. Я рекомендую тебе при генерации уникального ключа не ходить в БД для запроса уникальности. Лучше повторить запрос проанализировав ошибку, возвращенную `svc.store`

2023-12-13 19:33 UTC, s-shpak commented on internal/storage/memory/simple.go
> +		if _, err := m.Store(ctx, keys[i], urls[i], false); err != nil {
А что если коллизия произойдет во время добавления значений в `Store` ? Значения добавленные ранее там останутся ?

2023-12-13 19:33 UTC, s-shpak commented on internal/storage/postgres/config.go
> +		cfg.Logger.Warn("starting migration")
Это не уровень `Warn`, это либо `Info`, либо `Debug`. `Warn` предназначен для сообщений о чем-то плохом, но не критичном

2023-12-13 19:33 UTC, s-shpak commented on internal/storage/postgres/config.go
> +	if cfg.Migrate {
А зачем тебе вообще проверять, нужно ли запускать миграции ? Кажется, что их можно запускать при любом состоянии БД

2023-12-13 19:33 UTC, s-shpak commented on internal/storage/postgres/config.go
> +	pool, err := pgxpool.NewWithConfig(context.Background(), pCfg)
Контекст также должен приходить извне

2023-12-13 19:33 UTC, s-shpak commented on internal/storage/postgres/migrate.go
> +	if enforceDisableSSL {
Кажется, что этим не стоит управлять на уровне кода: лучше использовать ровно тот `dsn`, который передается программе

2023-12-13 19:33 UTC, s-shpak commented on internal/storage/postgres/postgres.go
> +type Postgres struct {
Я бы не выносил вовне информацию о том, что ты используешь `Postgres`. Лучше просто сказать, что ты работаешь с `БД`. Тогда, если в будущем БД поменяется, не надо будет менять везде имена

2023-12-13 19:33 UTC, s-shpak commented on internal/storage/postgres/postgres.go
> +func (pg *Postgres) StoreBatch(ctx context.Context, keys []string, urls []string) error {
Не очень удачный интерфейс, т.к. пользователь легко может передать `keys` и `urls` разного размера. Можно, например, заменить на `map`

2023-12-13 19:49 UTC, adwski commented on internal/storage/postgres/migrate.go
> +	if enforceDisableSSL {
тут есть конфликт дефолтных значений между pgx и lib/pg, который используется в миграции. pgx при неуказанном флаге sslmode подключается к БД без ssl, а миграция при этом падает с ошибкой ssl подключения (там require). https://github.com/lib/pq/issues/776
Я пробовал делать, чтобы migrate использовал pgx, но последний так не умеет. Поэтому решил сделать такой флаг.

2023-12-13 19:51 UTC, adwski commented on internal/storage/postgres/postgres.go
> +type Postgres struct {
Я так подумал, что раз используем pgx, а не database/sql, то можно сторадж назвать явно. Даже если это будет не postgres, то как минимум БД, которая работает с клиентами по этому протоколу

2023-12-13 19:52 UTC, adwski commented on internal/storage/postgres/postgres.go
> +func (pg *Postgres) StoreBatch(ctx context.Context, keys []string, urls []string) error {
Массивы быстрее и экономнее хэшей. Можно вставить проверку на равенство длины 🤔 ?

2023-12-13 19:53 UTC, adwski commented on internal/storage/postgres/config.go
> +	pool, err := pgxpool.NewWithConfig(context.Background(), pCfg)
Ага. Тут интерфейс конфигурации pgx мне немного не зашёл. Имхо в New() не должен передаваться контекст

2023-12-13 19:55 UTC, adwski commented on internal/storage/postgres/config.go
> +	if cfg.Migrate {
Я тут представляю еще процесс обновления, когда миграция запускается отдельный джобом, и соответственно в самом приложении выключена флагом. Скорее всего опять усложняю)

2023-12-13 19:59 UTC, adwski commented on internal/middleware/recovering/recovering.go
> +		// Doesn't work here for some reason
Так и не разобрался (но это не было повторным вызовом writeHeader). Уже переделал эту штуку

2023-12-13 20:01 UTC, adwski commented on docker/docker-compose.dev.yml
> +      - shorty-db:/var/lib/postgresql/data
Можно, но чем это лучше вольюма? Нет заморочек с fs permissions

2023-12-13 20:03 UTC, adwski commented on docker/docker-compose.dev.yml
> +    #  - ./db/init/:/docker-entrypoint-initdb.d/
для юзера и БД я обошёлся функционалом энтрипоинта, поэтому init скрипты не понадобились. В гит обычно не коммитят пустые директории, поэтому закоммитил это

2023-12-13 20:04 UTC, adwski commented on cmd/shortener/main.go
> +		zap.NewExample().Fatal("cannot configure app", zap.Error(err))
Хотел получить логгер без проверки ошибки. zap.L() ничего не выводил на самом деле

2023-12-13 20:12 UTC, adwski commented on internal/storage/postgres/postgres.go
> +type Postgres struct {
То есть в моём понимании если хотим добавить поддержку ещё одной БД, то это уже будет отдельный сторадж

2023-12-13 20:27 UTC, adwski commented on internal/middleware/recovering/recovering.go
> +		// Doesn't work here for some reason
Понял. Я вызывал метод метод своего writer-а вместо http.ResponseWriter

2023-12-16 17:19 UTC, adwski commented on internal/services/shortener/batch.go
> +func (svc *Service) shortenBatch(ctx context.Context, batch []BatchURL) ([]BatchShortened, error) {
переделал

2023-12-16 20:42 UTC, s-shpak requested changes

2023-12-16 20:42 UTC, s-shpak commented on cmd/shortener/init.go
> +	if err != nil {
Поправь логику проверки ошибок: эта ошибка должна проверяться раньше, и ты не можешь использовать `logger` для ее логгирования

2023-12-16 20:42 UTC, s-shpak commented on cmd/shortener/init.go
> +	defaultLogLevel = zapcore.DebugLevel
Обычно дефолтным левелом выставляется `Info`, но это минорное замечание

2023-12-16 20:42 UTC, s-shpak commented on cmd/shortener/init.go
> +		logLevel = os.Getenv(envLogLevel)
Я бы поменял логику получения дебаг левела:
1. если польователь его не передал используем дефолтный
2. если передал, пытаемся распарсить и при ошибке завершаем программу, т.к. если пользователь неправильно передал флаг конфигурации, ему стоит дать возможность сделать это корректно

Для реализации этого я бы использовал https://pkg.go.dev/os#LookupEnv

2023-12-16 20:42 UTC, s-shpak commented on cmd/shortener/init.go
> +			err = fmt.Errorf("cannot initialize file storage: %w", err)
А зачем логировать ошибку здесь ? Почему бы не сделать это на самом верхнем уровне ?

2023-12-16 20:42 UTC, s-shpak commented on cmd/shortener/main.go
> +		store, errS = initStorage(ctx, logger, cfg.StorageConfig)
Кажется, что называть ошибку как-то особенно нет смысла

2023-12-16 20:42 UTC, s-shpak commented on cmd/shortener/main.go
> +		logger.Fatal("cannot configure storage", zap.Error(errS))
Почему бы не пробросить ошибку на самый верхний уровень, до `main` и там зафаталиться. Тогда у тебя будет гарантия, что выходить из программы ты будешь всегда в одном месте

2023-12-16 20:42 UTC, s-shpak commented on internal/app/app.go
> +	statusSvc *status.Service) {
```suggestion
	statusSvc *status.Service,
) {
```

2023-12-16 20:42 UTC, s-shpak commented on internal/app/app_test.go
> +			shorty := NewShorty(zap.NewExample(), st, cfg)
Может все же https://pkg.go.dev/go.uber.org/zap#NewDevelopment ?

2023-12-16 20:42 UTC, s-shpak commented on internal/middleware/logging/logging.go
> +		rw.ResponseWriter.WriteHeader(http.StatusInternalServerError)
Эту ситуацию можно еще и залогировать

2023-12-16 21:01 UTC, adwski commented on cmd/shortener/init.go
> +		logLevel = os.Getenv(envLogLevel)
Тут еще есть нюанс, что ParseLevel парсит пустую строку в info без ошибки

2023-12-16 21:02 UTC, adwski commented on cmd/shortener/init.go
> +	defaultLogLevel = zapcore.DebugLevel
Я так сделал для учебного проекта, чтобы было больше инфы в тестах shortenertest

2023-12-16 21:02 UTC, adwski commented on cmd/shortener/init.go
> +			err = fmt.Errorf("cannot initialize file storage: %w", err)
Это fmt.Errorf

2023-12-16 21:11 UTC, adwski commented on cmd/shortener/init.go
> +	if err != nil {
Могу, потому что это ошибка парсинга logLvl. Логгер создаётся всегда без ошибок. Я бы предпочёл всю инфу выводить через логгер (поэтому и использую возможность его создать без обработки ошибок)

2023-12-16 21:36 UTC, adwski commented on internal/middleware/logging/logging.go
> +		rw.ResponseWriter.WriteHeader(http.StatusInternalServerError)
У самого rwWrapper нет логгера, но эта ошибка будет залогирована на 126й строке

2023-12-16 21:44 UTC, adwski commented on cmd/shortener/init.go
> +	defaultLogLevel = zapcore.DebugLevel
По той же причине оставил включенным pgx трейсеры

2023-12-16 21:46 UTC, adwski commented on cmd/shortener/init.go
> +	if err != nil {
Отрефакторил, чтобы было меньше "магии"

2023-12-16 21:47 UTC, adwski commented on cmd/shortener/init.go
> +		logLevel = os.Getenv(envLogLevel)
Изменил по предложенному сценарию

2023-12-16 21:49 UTC, adwski commented on cmd/shortener/init.go
> +			err = fmt.Errorf("cannot initialize file storage: %w", err)
Эта ошибка будет залогирована в main на 36й строке

2023-12-16 21:50 UTC, adwski commented on internal/app/app_test.go
> +			shorty := NewShorty(zap.NewExample(), st, cfg)
Поменял везде

2023-12-17 11:01 UTC, s-shpak commented on cmd/shortener/init.go
> +			err = fmt.Errorf("cannot initialize file storage: %w", err)
Сорри, неверно понял

2023-12-17 11:03 UTC, s-shpak approved these changes

2023-12-17 14:57 UTC, merged