Iter15
adwski/shorty pull request #12
Opened 2023-12-20 21:01 UTC by adwski

2023-12-21 11:42 UTC, s-shpak requested changes

2023-12-21 11:42 UTC, s-shpak commented on internal/app/app.go
> +		r.Group(func(r chi.Router) {
Не очень понимаю, зачем здесь вызов `Group`

2023-12-21 11:42 UTC, s-shpak commented on internal/auth/auth.go
> +func (a *Auth) GetUserFromJWT(signedToken string) (*user.User, error) {
Это не должно экспортироваться

2023-12-21 11:42 UTC, s-shpak commented on internal/auth/auth.go
> +	UID string
1. Зачем экспортировать это поле ?
2. Лучше его назвать `userID`, т.к. `UID` может восприниматься как `unique ID`

2023-12-21 11:42 UTC, s-shpak commented on internal/auth/auth.go
> +func (a *Auth) NewToken(u *user.User) (string, error) {
Не надо экспортировать

2023-12-21 11:42 UTC, s-shpak commented on internal/buffer/buffer.go
> +				s.buf = nil
Лучше переиспользовать существующий буффер через `s.buf = s.buf[0:0]`

2023-12-21 11:42 UTC, s-shpak commented on internal/buffer/buffer.go
> +	for {
В цикле много дупликации кода, попробуй упростить

2023-12-21 11:42 UTC, s-shpak commented on internal/buffer/buffer.go
> +				go func() {
Стартовать горутину здесь довольно опасно, т.к. если заполнение буффера станет намного более быстрым, чем flush, мы можем прийти к ситуации, когда количество горутин постоянно растет, что скажется на производительности решения. Я бы начал с синхронного флаша

2023-12-21 11:42 UTC, s-shpak commented on internal/middleware/auth/auth.go
> +	if err != nil {
Здесь я бы сначала проверил на `nil`

2023-12-21 11:42 UTC, s-shpak commented on internal/middleware/auth/auth.go
> +func (mw *Middleware) Chain(h http.Handler) *Middleware {
Ты не мог бы пояснить, зачем тебе этот метод ? Кажется, что он лишний, если используется `router.Use`

2023-12-21 11:42 UTC, s-shpak commented on internal/session/session.go
> +	u, ok = ctx.Value(ctxKeyUID).(*user.User)
Так тоже работает

```suggestion
	return ctx.Value(ctxKeyUID).(*user.User)
```

2023-12-21 11:42 UTC, s-shpak commented on internal/storage/database/database.go
> +	// https://youtu.be/sXMSWhcHCf8?t=995
круто

2023-12-21 20:06 UTC, adwski commented on internal/auth/auth.go
> +	UID string
Для marshall json разве не нужно? 🤔

2023-12-24 17:08 UTC, s-shpak requested changes

2023-12-24 17:08 UTC, s-shpak commented on internal/buffer/buffer.go
> +	if len(s.buf) > 0 {
Здесь лучше сначала проверить на `len(s.buf) == 0`

2023-12-24 17:08 UTC, s-shpak commented on internal/buffer/buffer.go
> +		copy(flushed, s.buf)
Я бы не копировал буфер. Я бы отдавал готовый slice функции flush и инициализировал новый пустой буффер. Каежтся, что так должно работать быстрее

2023-12-24 20:25 UTC, adwski commented on internal/buffer/buffer.go
> +		copy(flushed, s.buf)
Ага. Копирование осталось от изначального подхода, где флаш происходил асинхронно. Сейчас поскольку мы лочимся, это и правда лишнее

2023-12-25 14:51 UTC, s-shpak requested changes

2023-12-25 14:51 UTC, s-shpak commented on internal/buffer/buffer.go
> +	s.buf = s.buf[0:0]
Теперь так делать нельзя, см. пример почему: https://go.dev/play/p/8G50GTvJ73U

Если будет неясно, та задай вопрос - обсудим

2023-12-25 18:47 UTC, adwski commented on internal/buffer/buffer.go
> +	s.buf = s.buf[0:0]
Мне кажется тут больше такая ситуация https://go.dev/play/p/ajwaEP71dPI
Между отсылкой сигнала на флаш буффера по заполнению и непосредственно флашем есть лаг и сообщения могут добавиться сверху. Думаю, что это допустимо. Операции с буффером находятся под мьютексом, так что перезаписать данные, которые ещё не флашнуты, мы не можем. Добавил тесты для подтверждения того, что все сообщения проходят через буффер без потерь. 

Кроме этого тесты выявили дедлок, который пофиксил

2023-12-26 23:32 UTC, s-shpak requested changes

2023-12-26 23:32 UTC, s-shpak commented on internal/buffer/buffer.go
> +	s.buf = s.buf[0:0]
Я пока не понял, как это изменение фиксит такую проблему: https://go.dev/play/p/5DhVjbNI9fI

2023-12-27 07:25 UTC, adwski commented on internal/buffer/buffer.go
> +	s.buf = s.buf[0:0]
Понял про что ты. Сделал make на каждом флаше, чтобы позволить вызываемому коду асинхронно делать что-то с данными.

2023-12-27 10:19 UTC, s-shpak approved these changes

2023-12-27 10:57 UTC, merged