Iter5
adwski/shorty pull request #5
Opened 2023-10-30 19:53 UTC by adwski

Added:
- app server
- redirector service
- shortener service
- validators
- storage interface and simple in-memory storage

2023-10-31 22:31 UTC, s-shpak requested changes

2023-10-31 22:31 UTC, s-shpak commented on cmd/shortener/main.go
> +	var (
В Го не принято объявлять переменные в начале функции, объявляй их там, где они возникают (на строке 18 в текущей версии)

2023-10-31 22:31 UTC, s-shpak commented on cmd/shortener/main.go
> +		log.WithError(err).Fatal("cannot configure app")
Вообще, лучше инициализировать логгер и использовать его, а не глобальный

2023-10-31 22:31 UTC, s-shpak commented on cmd/shortener/main.go
> +		os.Exit(1)
А для этого и нужна функция `Fatal`, которая сама вызовет `os.Exit(1)`

2023-10-31 22:31 UTC, s-shpak commented on internal/app/app.go
> +			ReadTimeout:       defaultTimeout,
Почитай эту статью, чтобы лучше выбрать таймауты: https://adam-p.ca/blog/2022/01/golang-http-server-timeouts/

2023-10-31 22:31 UTC, s-shpak commented on internal/app/app.go
> +			MaxHeaderBytes:    8 * http.DefaultMaxHeaderBytes,
Как ты выбрал это значение?

2023-10-31 22:31 UTC, s-shpak commented on internal/app/app.go
> +	router.Trace("/printDB", sh.handlePrintDB)
Такие вещи не должны попадать в PR в таком виде -- это небезопасно. По дефолту этот эндпоинт должен быть отключен, подключаться он должен опционально. Хотя это в целом выглядит опасно, потому на реальном проекте это не попало бы в PR

2023-10-31 22:31 UTC, s-shpak commented on internal/app/app_test.go
> +	for _, url_ := range urls {
```suggestion
	for _, u := range urls {
```

2023-10-31 22:31 UTC, s-shpak commented on internal/app/config/config.go
> +		//listenAddr     = flag.String("listen", ":8080", "listen address")
Комментарии надо удалять

2023-10-31 22:31 UTC, s-shpak commented on internal/app/config/config.go
> +	log "github.com/sirupsen/logrus"
Не вижу смысла объявлять здесь псевдоним: это чтобы сделать код короче?

2023-10-31 22:31 UTC, s-shpak commented on internal/app/config/config.go
> +	*listenAddr = envOverride("SERVER_ADDRESS", *listenAddr)
Лучше использовать не `flag.String`, а `flag.StringVar`: в коде будет меньше работы с указателями (тебе надо будет взять адрес в одном месте вместо трех разыменований указателей)

2023-10-31 22:31 UTC, s-shpak commented on internal/app/config/config.go
> +	if newVal = os.Getenv(name); newVal == "" {
Лучше использовать `LookupEnv`, т.к. пустое значение и незаданное значение могут иметь разное значение с т.з. логики приложения

2023-10-31 22:31 UTC, s-shpak commented on internal/app/app.go
> +	router.Get("/{path}", redirector.New(&redirector.Config{
Сейчас ты каждый раз при получении нового запроса инициализируешь новый `redirector`, это не требуется, инициализируй объект один раз и используй его метод

2023-10-31 22:31 UTC, s-shpak commented on internal/app/app.go
> +	router.Post("/", shortener.New(&shortener.Config{
См. комментарий про новый `redirector`

2023-10-31 22:31 UTC, s-shpak commented on internal/services/redirector/redirector.go
> +func (svc *Service) Redirect(w http.ResponseWriter, req *http.Request) {
Мне не очень нравится, что ты назвал сервис редиректором: то, что мы делаем редирект на ресурс - деталь имплементации, она может поменяться независимо от логики. В твоем же случае логика и редирект тесно связаны.

Что можно сделать:
1. переименовать сервис
2. разнести REST-логику и бизнес-логику (необязательно, и на предстоящем вебинаре обсудим как)

2023-10-31 22:31 UTC, s-shpak commented on internal/services/redirector/redirector.go
> +		log.WithError(err).Error("cannot get redirect")
А если URL просто не найдена, то ошибку все равно надо логировать?

2023-10-31 22:31 UTC, s-shpak commented on internal/services/redirector/redirector_test.go
> +				_ = svc.store.Store(k, v)
Ошибки надо проверять, даже если они не связаны с логикой теста: тест не имеет смысл продолжать, если произошла ошибка

2023-10-31 22:31 UTC, s-shpak commented on internal/services/shortener/shortener.go
> +	return svc.servedScheme + "://" + svc.host + "/" + shortPath
Есть несколько способов как это оптимизировать. Пока достаточно просто использовать `fmt.Sprintf` - это, как минимум, сделает код более читаемым

2023-10-31 22:31 UTC, s-shpak commented on internal/services/shortener/shortener.go
> +		log.WithError(err).Error("cannot store url")
После этого надо выйти из функции

2023-10-31 22:31 UTC, s-shpak commented on internal/storage/common/errors.go
> +func ErrNotFound() error {
1. Идиоматично будет:

```suggestion
var ErrNotFound = errors.New("not found")
```

2. Мне не нравится, что  пакет называется `common`: непонятно для чего он. Лучше назови пакет `errors` и работай с ним

2023-10-31 22:31 UTC, s-shpak commented on internal/storage/generators/generators.go
> +	for i = 0; i < length; i++ {
Я бы упростил: создал бы алфавит символов и выбирал бы случайный символ из него

2023-10-31 22:31 UTC, s-shpak commented on internal/storage/simple/simple.go
> +func (si *Simple) Get(key string) (url string, err error) {
Эта операция небезопасна для конкурентного исполнения

2023-10-31 22:31 UTC, s-shpak commented on internal/storage/simple/simple.go
> +		key = generators.RandString(si.keyLen)
1. Не хорошо, что мы генерируем случайный ключ заблокировавшись на мьютексе, кажется, что это не нужно
2. Почему store вообще знает о генераторах, URL и т.п.: по идее он должен только уметь сохранять и извлекать сохраненные данные

2023-10-31 22:31 UTC, s-shpak commented on internal/storage/simple/simple.go
> +func (si *Simple) Dump() string {
Это я бы просто убрал: для такого существуют дебагеры

2023-10-31 22:31 UTC, s-shpak commented on internal/storage/simple/simple.go
> +func (si *Simple) DumpMap() map[string]string {
См. предыдущий комментарий + неправильно, что функционал приложения включает метод, который используется исключително в тестах

2023-10-31 22:31 UTC, s-shpak commented on internal/storage/storage.go
> +	Dump() (data string)
Не нужен в интерфейсе

2023-10-31 22:31 UTC, s-shpak commented on internal/storage/storage.go
> +	DumpMap() map[string]string
Не нужен в интерфейсе

2023-10-31 22:31 UTC, s-shpak commented on internal/storage/storage.go
> +type Storage interface {
А зачем ты объявил интерфейс?

2023-10-31 22:31 UTC, s-shpak commented on internal/validate/validate.go
> +func ErrInvalidChar() error {
1. См. предыдущий комментарий о том, как объявлять ошибку
2. Зачем тебе как-то по-особенному определять эту ошику, почему нельзя просто использовать `fmt.Errorf`?

2023-10-31 22:31 UTC, s-shpak commented on internal/validate/validate.go
> +	return errors.New("incorrect or missing Content-Length")
Стоит различать `incorrect` и `missing` значения

2023-11-02 20:17 UTC, adwski commented on internal/app/app_test.go
> +	for _, url_ := range urls {
Поменял имена, u уже есть внутри цикла

2023-11-02 20:19 UTC, adwski commented on internal/app/config/config.go
> +	log "github.com/sirupsen/logrus"
Да, так выглядит почти как замена стандартному логгеру. Взял из ридми logrus. После изменения на отдельный логгер смысла особого не имеет, убрал

2023-11-02 20:19 UTC, adwski commented on internal/app/app.go
> +	router.Get("/{path}", redirector.New(&redirector.Config{
Это не так)

2023-11-02 20:20 UTC, adwski commented on internal/app/app.go
> +	router.Post("/", shortener.New(&shortener.Config{
тут тоже всё ок

2023-11-02 20:22 UTC, adwski commented on internal/services/redirector/redirector.go
> +func (svc *Service) Redirect(w http.ResponseWriter, req *http.Request) {
Это архитектурное решение вынести часть сервиса в отдельную сущность, имеющую потенциал работать на высокой нагрузке

2023-11-02 20:24 UTC, adwski commented on internal/storage/storage.go
> +type Storage interface {
Уровень абстракции. В будущем позволит бизнес логике работать с разными типами стораджей

2023-11-02 20:25 UTC, adwski commented on internal/validate/validate.go
> +func ErrInvalidChar() error {
Считаю хорошей практикой все возможные ошибки выносить в сущности для возможной последующей работы с ними в логике и тестах

2023-11-02 20:32 UTC, adwski commented on cmd/shortener/main.go
> +		log.WithError(err).Fatal("cannot configure app")
Переделал везде на использование отдельного логгера. Но это место единственное, где логгера может не быть, поэтому конкретно тут оставил глобальный

2023-11-02 20:45 UTC, adwski commented on internal/storage/storage.go
> +type Storage interface {
Плюс кстати такое позволяет явно разграничить домены и избежать случайных некорректных кроссзависимостей

2023-11-03 21:24 UTC, s-shpak commented on internal/services/redirector/redirector.go
> +func (svc *Service) Redirect(w http.ResponseWriter, req *http.Request) {
В этом случае я бы просто назвал его, наример, `URLResolver`: нам необязательно редиректить клиента, вдруг мы решим в будущем просто отдавать клиенту URL в боди

2023-11-03 21:27 UTC, s-shpak commented on internal/validate/validate.go
> +func ErrInvalidChar() error {
Здесь, с моей т.з., стоит применить принцип YAGNI и, пока это нигде не используется, не добавлять это в кодувую базу

2023-11-03 21:27 UTC, s-shpak requested changes
См. комментарии к оставшимся тредам

2023-11-04 08:13 UTC, adwski commented on internal/validate/validate.go
> +func ErrInvalidChar() error {
Сейчас эти ошибки используются в validate_test.go, где удостоверяемся что делаем нужные проверки и возвращаем соответствующие ошибки

2023-11-04 08:17 UTC, adwski commented on internal/services/redirector/redirector.go
> +func (svc *Service) Redirect(w http.ResponseWriter, req *http.Request) {
По заданию пока только редирект. В будущем в зависимости от функционала действительно можем дополнить и при необходимости переименовать сервис, либо создать отдельный. Переименовал в Resolver

2023-11-04 16:26 UTC, s-shpak commented on internal/validate/validate.go
> +func ErrInvalidChar() error {
1. Логика, которая используется в тестах и только в тестах не должна попадать в кодовую базу
2. Ты возвращаешь ошибку только одного типа из функции
3. Когда ты определяешь экспортируемую ошибку, ты хочешь сообщить пользователю пакета, что произошла именно эта ошибка, потому что ты предполагаешь, что он сможет как-то ее обработать. Это подразумевается в данном случае?

В тестах достаточно проверять сообщение об ошибке, если ошибка не определена как отдельный тип/переменная

2023-11-04 16:27 UTC, s-shpak requested changes
См. последний комментарий

2023-11-04 16:48 UTC, adwski commented on internal/validate/validate.go
> +func ErrInvalidChar() error {
Ранее там была еще проверка на Content-Type, которую пришлось убрать. Сейчас эти ошибки только для сообщения, что именно не так. В общем случае функции пакета используются для понимания, валиден аргумент или нет (до вынесения их в отдельный пакет возвращали bool)

2023-11-04 17:03 UTC, adwski commented on internal/validate/validate.go
> +func ErrInvalidChar() error {
Убрал глобальные ошибки

2023-11-05 07:44 UTC, s-shpak requested changes

2023-11-05 07:44 UTC, s-shpak commented on internal/validate/validate.go
> +		err = errors.Join(errors.New("incorrect Content-Length"), err)
Более лаконичный способ обернуть ошибку:

```suggestion
		err = fmt.Errorf("incorrect Content-Length: %w", err)
```

2023-11-05 07:44 UTC, s-shpak commented on internal/validate/validate_test.go
> +		err  string
```suggestion
		errMsg  string
```

2023-11-05 09:37 UTC, adwski commented on internal/validate/validate.go
> +		err = errors.Join(errors.New("incorrect Content-Length"), err)
Согласен, исправил

2023-11-05 09:37 UTC, adwski commented on internal/validate/validate_test.go
> +		err  string
Переименовал

2023-11-05 18:02 UTC, s-shpak approved these changes

2023-11-05 18:54 UTC, merged