Iter9
adwski/shorty pull request #9
Opened 2023-11-19 21:19 UTC by adwski

2023-11-21 17:48 UTC, s-shpak requested changes

2023-11-21 17:48 UTC, s-shpak commented on Dockerfile
Я бы не рекомендовал делать multistage билд в данном случае: пока в докере сервис будет запускаться локально, а это значит, что `builder` будет оставаться в локальном кэше имеджей. На реальном проекте в начале я бы использовал один и тот же image (и попытался сделать бы его минимальным по размеру, конечно).

Alpine тоже стоит использовать с осторожностью

2023-11-21 17:48 UTC, s-shpak commented on Makefile
> +goimports:
.PHONY

2023-11-21 17:48 UTC, s-shpak commented on cmd/shortener/main.go
> +	signal.Notify(c, os.Interrupt)
Посмотри в сторону `NotifyContext`

2023-11-21 17:48 UTC, s-shpak commented on internal/app/app.go
> +	case config.StorageKindFile:
Мне не очень нравится, что Shorty знает, какой Storage запускается. Почему бы не заинджектить Storage в Shorty извне ?

Тогда не нужен Runnable - у Storage должен быть метод Close, который реализует graceful shutdown. Graceful Shutdown'ом лучше управлять там же, где ты им управляешь для Shorty

2023-11-21 17:48 UTC, s-shpak commented on internal/app/app.go
> +	chain := requestid.New(&requestid.Config{Generate: cfg.GenerateReqID}).Chain(
Чем этот подход лучше, чем использование `router.Use` ?

2023-11-21 17:48 UTC, s-shpak commented on internal/app/app.go
> +type srvLogger struct {
Это можно заменить вызовом `logger.With`

2023-11-21 17:48 UTC, s-shpak commented on internal/app/app.go
> +	for {
Это слишком сложно. Почему бы не использовать WaitGroup ? и я рекомендую собрать логику graceful shutdown в одном месте

2023-11-21 17:48 UTC, s-shpak commented on internal/app/config/config.go
> +	StorageKindSimple = iota
Вообще, такие вещи должны быть определены в пакете `storage/config`

2023-11-21 17:48 UTC, s-shpak commented on internal/generators/generators.go
> +	if _, err := crand.Read(b); err != nil {
Я бы не использовал здесь `crypto/rand`: он менее эффективен чем `math/rand` и не нужен в это use-case

2023-11-21 17:48 UTC, s-shpak commented on internal/middleware/compress/compress.go
> +func (rw *rwWrapper) Header() http.Header {
Для имплементации недостающих для интрефейа методов можно использовать композицию

2023-11-21 17:48 UTC, s-shpak commented on internal/middleware/requestid/requestid.go
> +		// error will happen only if ReadFull() fails
Возможно, стоит залогировать ошибку здесь, чтобы ответить на этот  вопрос

2023-11-21 17:48 UTC, s-shpak commented on internal/services/shortener/service.go
> +	return
не нужен

2023-11-21 17:48 UTC, s-shpak commented on internal/storage/file/file.go
> +type Store struct {
А почему бы не использовать in-memory реализацию и обернуть ее логикой работы с файлом ?

2023-11-21 18:37 UTC, adwski commented on internal/app/app.go
> +	case config.StorageKindFile:
Runnable больше для "запуска" с передачей контекста (через New() его передавать не ок), Close - это больше следствие того, что то, что запустилось, нужно остановить gracefully

2023-11-21 18:38 UTC, adwski commented on internal/app/app.go
> +	chain := requestid.New(&requestid.Config{Generate: cfg.GenerateReqID}).Chain(
Просто не знал)

2023-11-21 18:40 UTC, adwski commented on internal/generators/generators.go
> +	if _, err := crand.Read(b); err != nil {
gosec рекомендует использование crypto/rand, поэтому его добавил

2023-11-21 18:41 UTC, adwski commented on internal/storage/file/file.go
> +type Store struct {
Думал об этом, но решил не делать "горизонтальных" зависимостей

2023-11-21 18:51 UTC, adwski commented on Dockerfile
Может сделать тогда несколько таргетов dev и prod? Локально использовать dev, который будет конечным состоянием builder-а

2023-11-21 18:55 UTC, adwski commented on internal/storage/file/file.go
> +type Store struct {
Ещё формат записи в файл не соотносится тем, что в simple in-memory

2023-11-24 20:47 UTC, adwski commented on internal/services/shortener/service.go
> +	return
нужен)

2023-11-24 20:55 UTC, adwski commented on internal/generators/generators.go
> +	if _, err := crand.Read(b); err != nil {
Уберу. Вообще думаю в будущем перекатиться на хэш функцию

2023-11-24 21:03 UTC, adwski commented on internal/app/app.go
> +type srvLogger struct {
Внутрь добавить можно. Но сам объект для имплементации Write-а, чтобы передать стандартному логгеру

2023-11-25 12:49 UTC, adwski commented on internal/app/config/config.go
> +	StorageKindSimple = iota
Убрал

2023-11-25 12:49 UTC, adwski commented on internal/storage/file/file.go
> +type Store struct {
Сделал переиспользование через композицию

2023-11-27 18:53 UTC, s-shpak requested changes

2023-11-27 18:53 UTC, s-shpak commented on internal/app/app.go
> +type srvLogger struct {
Это для middleware ? если да, то лучше объявлять структуру рядом с кодом `middleware`

2023-11-27 18:53 UTC, s-shpak commented on report.xml
Этот файл точно нужен в репозитории ?

2023-11-27 18:53 UTC, s-shpak commented on internal/app/config/mockconfig/mock_Storage.go
Лучше поменять имя на `mock_storage.go`

2023-11-27 20:42 UTC, adwski commented on report.xml
Случайно попал. Убрал

2023-11-27 20:43 UTC, adwski commented on internal/app/config/mockconfig/mock_Storage.go
Изменил конфиг, сгенерировал заново

2023-11-27 23:31 UTC, s-shpak approved these changes

2023-11-28 06:40 UTC, merged